apiVersion: apps/v1
kind: Deployment
metadata:
  name: reco
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reco
  template:
    metadata:
      labels:
        app: reco
    spec:
      containers:
      - image: okteto.dev/reco:latest
        name: reco
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "921829eb-6a4d-42ce-b085-c338463bc4e7"
        - name: Vless_Path
          value: "/921829eb-6a4d-42ce-b085-c338463bc4e7"
        - name: Vmess_UUID
          value: "97e84d01-6f41-403f-ac10-f515f26d651e"
        - name: Vmess_Path
          value: "/97e84d01-6f41-403f-ac10-f515f26d651e"
        - name: Share_Path
          value: "/v2link"
